library(MetaboAnalystR)
rm(list = ls())

mSet<-InitDataObjects("conc", "stat", FALSE)
Meta_data <- Read.TextData(mSet, "data_2.csv", "colu", "disc")
mSet<-SanityCheckData(Meta_data)
mSet<-ReplaceMin(mSet)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "NULL", "LogNorm", "MeanCenter", "S10T0", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "_norm_0_", format ="png", dpi=72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "_snorm_0_", format = "png", dpi=72, width=NA)
mSet<-FC.Anal(mSet, 2.0, 0, FALSE)
mSet<-Ttests.Anal(mSet, nonpar=F, threshp=0.05, paired=TRUE, equal.var=TRUE, "fdr", FALSE)
mSet<-Volcano.Anal(mSet, TRUE, 2.0, 0, F, 0.1, TRUE, "raw")
mSet<-PlotVolcano(mSet, "_volcano_0_", 1, 0, format ="png", dpi=72, width=NA)
mSet <- ANOVA.Anal(mSet, F, 0.05, "fisher")
mSet<-PlotStaticHeatMap(mSet, "heatmap_1_", "png", 300, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8, 8, "overview", T, T, NULL, T, F, T, T, T)